#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")"

export PROJMAN_DB="projman-test.db"
export PROJMAN_PORT=${PROJMAN_PORT:-18080}
# Clear previous test DB
./clear-test-db || true

# Start auto-reloading server on the test DB and test port
./dev-server
